### ISSUE TITLE
Services - 2D Grid

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#12]
Discussion with others on how best to approach this using grid! 
Looking to practically apply grid on this page and project with a focus on 2D (column/row) 

**QUESTIONS**
Is it best to make the white space a row or margin ? 
![image](https://user-images.githubusercontent.com/32041993/52905135-ab721700-31ea-11e9-9c61-2fb6f239a339.png)

It is apparent there are three columns: 
![image](https://user-images.githubusercontent.com/32041993/52905158-086dcd00-31eb-11e9-95bf-070422bce29e.png)

_Originally posted by @suziebytes in https://github.com/suziebytes/Resswell/issues/6#issuecomment-464385007_

**Comment by suziebytes** [comment]
- How many rows? 
- How many columns?

![services mockup](https://user-images.githubusercontent.com/32041993/52905020-a744fa00-31e8-11e9-8d63-8f9bfe3fb265.jpg)

**Comment by suziebytes** [comment]
So I took a break and ended up watching this:
https://scrimba.com/g/gR8PTE


Great tutorial on CSS grid with short videos on different concepts of the grid. 
Explains why doing xyz is better than something else. Enjoy it! 
 
Better understanding of grids. Updated grid plan using `grid-areas`
There are 
11 rows  
9 different elements on the page designated by the letter
![image](https://user-images.githubusercontent.com/32041993/52908907-97063c80-3233-11e9-943c-08a7df0151ae.png)

**Comment by suziebytes** [comment]
So after creating the code for this last night using `grid-area` 

Issues: 

- images being too big and taking up too much space 
- images are so big that there is now a horizontal scroll bar to account for all the content 

```css
.servicescontainer {
    display: grid;
    height: 100%;
    grid-template-columns: repeat(3, minmax(100px, auto-fit));
    grid-template-rows: repeat(11, minmax(20px, auto));
    grid-template-areas:
        /* "h h h" */
        "g s b"
        "g s b"
        "g k l"
        "g k l"
        "g k l"
        "g k l"
        "g k l"
        "c k l"
        "c k m";
    /* "f f f"; */
    grid-gap: 4px;
}
```
![image](https://user-images.githubusercontent.com/32041993/52920125-0f194480-32be-11e9-998b-40fb5fa04238.png)
