### ISSUE TITLE
Contact Page 

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#13]
Created the following mockup: 
![contact mockup](https://user-images.githubusercontent.com/32041993/53038111-c03fec00-3430-11e9-9706-1a0e4052cd1a.jpg)

I have sectioned it as the following: 
<img width="929" alt="screen shot 2019-02-19 at 10 21 16 am" src="https://user-images.githubusercontent.com/32041993/53038126-cc2bae00-3430-11e9-8e40-155011815891.png">

From this I can either use `grid` or `flexbox`. 

 **GOALS FOR THIS LESSON**
- Learn to create forms  & style forms 
- Use flex-box 
- CSS Application 

--- hover -> sidebar slides out with more content (social media?)- utilize transitions [(example)
](https://www.w3schools.com/howto/howto_css_sidenav_buttons.asp)

- JS Application 
---use JS to run through email input to check for '@'  
--- Popup to confirm when `send` button is successful 

>  you can make the popup in the code
and then add a classname when it's confirmed
and on the extra classname on css make it visible
while before confirmed the popup would be not visible
and use something like the z-index

**Comment by suziebytes** [comment]
Got the code to create a grid layout. 
I am now working on the form aspect of this. My current approach is to create it with grid. 

Currently, I don't know why the `.message` isn't taking up two rows as seen in my `grid-area`

```css
.formcontents {
    display: grid;
    grid-template-columns: 1f2 2fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-template-areas:
        "first message"
        "email message"
        ". button";
    background: white;
    margin: 3% 10%;
    padding: 10px;
}
```


```html
<div class="form">
            <form class="formcontents">
                <div class="first">Name: <br>
                    <input type="text"><br>
                </div>

                <div class="email">
                    Email: <br>
                    <input type="text"> <br>
                </div>
                <div class="message">
                    Message: <br>
                    <input type="text">
                </div>
                <input class="button" type="submit" value="SEND">
                <form>

        </div>
```

![image](https://user-images.githubusercontent.com/32041993/53055552-fabf7e00-345c-11e9-9a40-1cd2e66248a0.png)

**Comment by suziebytes** [comment]
Well.. that was stupid *doh* 

I had set the each class to `grid-column` instead of `grid-area`
Corrected: 

```css 
.first {
    grid-area: first;
    background: skyblue;
}

.email {
    grid-area: email;
    background: yellow;
}

.message {
    grid-area: message;
    background: orange;
}

.button {
    grid-area: button;
    background: pink;
}
```

![image](https://user-images.githubusercontent.com/32041993/53056977-24c76f00-3462-11e9-88b8-c749d6e8ea2f.png)

**Comment by suziebytes** [comment]
Horray. 
Added some styling to the form and now we are here. 

I need to still  need to figure out: 

- how to isolate this button for the contact page as it is assuming the style from about page 
- justify the button to the right of the form box 
- I also didn't realize that I had put the button outside of the `.formcontent` on my mock up, so I might keep it there or I might make the change so it's as close as possible to the mock up
- my `.message` section is assuming the 2 rows that it is suppose to take up based on the `grid area`, but the input field is not taking up the 2 rows like my mock up

![image](https://user-images.githubusercontent.com/32041993/53070265-6de3e700-3493-11e9-812a-98aaa971f7e2.png)

**Comment by suziebytes** [comment]
Currently working on trying to get the message  text field to span the two rows. 

Have tried variations with a recent one: 
```css
---adding messagefield
grid-template-areas:
        "first message"
        "email messagefield"
        ". button";

---selecting the input
input [type="text"] {
    grid-area: messagefield;
}
```

I've also put the message input into a `<div>`, but it didn't work 
```html
 <div class="message">
                    Message: <br>
                    <div class="messagefield"><input type="text"></div>  -------- HERE
                </div>
```

**Comment by suziebytes** [comment]
Still having issue with getting the message text field to expand with the size of the two rows. 
Someone had set the size manually using css to selec the text input: 
```css
   width: 97%;
    height: 70%;```
 
This works, but I wanted to know **how can this be done with grid? can it be done?** 
I assumed that by have `.message` = `2fr` rows then it would give it more space to grow.

Right now this is the current update: 
`button` moved out of the `.formcontents` 
 `<form>`  added to contain 1. `formcontents` and 2. `<button>` 
The new `<form>` set to `display:grid` with two rows 
--> ` row for `formconents` 
--> `row for `<button>` 

Results:
![image](https://user-images.githubusercontent.com/32041993/53122126-b38fc680-350a-11e9-87c3-d01eac46217b.png)



Issues: 
- Getting button to align on the right side. Have tried 
`justify-self``
justify-content/items`
`align-content/items` 
and tried setting to `right` as well as `end`.  Doesn't work and now I'm not sure why

- Getting the message field to span over the two rows using `grid-area` or something related to grid. Or is it really just easier and better to manually set `width/height`?

**Comment by suziebytes** [comment]
I realized the reason why `justify-self:end` didn't work was because there was already margins set on the `form content` which covers the email, message, name fields, but not the button.  
 
By removing the margins in `formcontent` and then putting the `margin` settings in the `<form>` that is the container for: 
1.  `.formcontents` 
2. `<button>`

`justify-self:end` works 

```css
form {
    display: grid;
    grid-template-rows: auto 35px;
    margin: 3% 10%;
}


.formcontents {
    display: grid;
    grid-template-columns: 1fr 2fr;
    grid-template-rows: 1fr 1fr;
    grid-template-areas:
        "first message"
        "email message";
}

button {
    box-shadow: 3px 3px 3px 3px #ccc;
    font-size: 10pt;
    color: black;
    background-color: white;
    justify-self: end;  <----- ADDED 
    margin-top: 2%; <------- ADDED to create space between the form fields and button 
} 


```

![image](https://user-images.githubusercontent.com/32041993/53128083-d7f29f80-3518-11e9-999a-5807e5c0e95e.png)

**Issues**
- The 'send' button is still not looking the right size 
- Can we use grid to make the message text field span two rows? If I can't figure this out I am going to just manually adjust h/w using % for this so I can move on. 
👎
