### ISSUE TITLE
Navigation Hover Effect

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#3]
add hover effect on navigation 

**Style option 1:** Reference: https://www.youtube.com/watch?v=FEmysQARWFU&t=21s
**Style option 2:** 
On hover, button is highlighted gray, text white  
 
Example: 
![image](https://user-images.githubusercontent.com/32041993/52744881-a450cc00-2f92-11e9-98a2-47fff4f7f6a8.png)

**Comment by suziebytes** [comment]
RESOLVED: 

```css 

a:hover {
    color: white;
    background: #c9c9c9;
} 
```

**Comment by suziebytes** [comment]
Realized that the hover was effecting the logo. 
Logo would turn grey upon hover. 

Changed css to specify links only: 
```css

ul>li>a:hover {
    color: white;
    background: #c9c9c9;
}
```
