### ISSUE TITLE
Logo Details 

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#4]
Convert logo image into SVG using https://vectormagic.com/

Add in ' Property Management ' under the logo

**Comment by suziebytes** [comment]
vectormagic.com is not free. 
Created a new logo via PSD w/ 1000px x 1000px 

Removed `<img src='path'> from `html` page  
Added the following `css` properties: 

```css
.logo {
    display: block;
    background-image: url('resswell logo 2');
    background-size: cover;
    height: auto;
    max-width: 100%;
}
```

Image now shows up, but full height is not showing. 
<img width="1276" alt="screen shot 2019-02-13 at 12 44 45 pm" src="https://user-images.githubusercontent.com/32041993/52742798-68673800-2f8d-11e9-901a-e48debd37344.png">

**Comment by suziebytes** [comment]
RESOLVED!! 

Padding on original was 100px. 
Image is 200px by 200px so 100px was cut off. 

Updated 
```css  
.logo {
    display: block;
    background-image: url('resswell logo 2');
    background-size: cover;
    height: auto;
    max-width: 100%;
    padding-bottom: 200px;
    opacity: .6;
}
```

![screen shot 2019-02-13 at 12 50 38 pm](https://user-images.githubusercontent.com/32041993/52743154-3efadc00-2f8e-11e9-99ec-d51a41eb1d2d.png)
