### ISSUE TITLE
About Page - Moving Section Links 

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#5]
How to move the section links box up on top of the background for section text?

```html 
<main class="about">
        <div class="txtbg"></div>
        <!-- flexbox container -->
        <div class='container'>
            <section class="about">ABOUT</section>
            <section class="services">SERVICES</section>
            <section class="why">WHY RESSWELL</section>
        </div>

    </main>
```

```css 

div.container {
    display: inline flex;
    font-family: arial;
    color: white;
    font-size: 11pt;
    font-weight: 50;
    text-align: center;
    width: 200px;
    margin-left: 35%;
    margin-top: 12%;
    opacity: .95;
}

.txtbg {
    display: block;
    background-color: white;
    opacity: .8;
    margin-left: 45%;
    margin-top: 8%;
    height: 230px;
    width: 600px;
}

section.about {
    background-color: #626262;
    padding-top: 10px;
    padding-bottom: 10px;
}

section.services {
    background-color: #b7b7b7;
    padding-top: 10px;
    padding-bottom: 10px;
}

section.why {
    background-color: #e3e3e3;
    padding-top: 10px;
    padding-bottom: 10px;
} 
```

![about - box order](https://user-images.githubusercontent.com/32041993/52762170-42f91f00-2fcb-11e9-99ed-22468468bca5.jpg)

**Comment by suziebytes** [comment]
Didn't realize I had margins in there. 
Removed margin, added `padding-left` 

but the top has a space. 

![image](https://user-images.githubusercontent.com/32041993/52762355-0aa61080-2fcc-11e9-98d8-9d09d68f362b.png)

**Comment by suziebytes** [comment]
NEW IDEA: 
Going to make a small little mini navigation on top of the section content box in white 
WHY: UX design is better for navigating page 

![about mockup update](https://user-images.githubusercontent.com/32041993/52762679-79379e00-2fcd-11e9-9451-6ee3a69e563c.jpg)

**Comment by suziebytes** [comment]
Switched back to using grid 
Trying to get the rows to be in columns by doing 1fr, but this didn't work.

```css
.container {
    grid-template-columns: 1fr 1fr 1fr;
    font-family: arial;
    color: white;
    font-size: 11pt;
    font-weight: 50;
    text-align: center;
    opacity: .6;
    margin-left: 45%;
    margin-top: 4%;
    width: 600px;
    background-color: white;
    height: 300px;
    box-shadow: 2px 2px grey;
}
```

<img width="1040" alt="screen shot 2019-02-13 at 8 40 09 pm" src="https://user-images.githubusercontent.com/32041993/52763168-92d9e500-2fcf-11e9-9c56-a48b38fb9911.png">

**Comment by suziebytes** [comment]
```css 

.aboutnav {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    font-family: arial;
    color: white;
    font-size: 11pt;
    font-weight: 50;
    text-align: center;
    opacity: .6;
    margin-left: 45%;
    margin-top: 4%;
    width: 600px;
    background-color: white;
    height: 300px;
    box-shadow: 2px 2px grey;
}

.about {
    background-color: #626262;
    padding-top: 10px;
    padding-bottom: 10px;

}

.services {
    background-color: #b7b7b7;
    padding-top: 10px;
    padding-bottom: 10px;
}

.why {
    background-color: #e3e3e3;
    padding-top: 10px;
    padding-bottom: 10px;

}
```

```html 
        <nav class="aboutnav">
            <ul style="list-style:none">
                <li class="about">ABOUT</li>
                <li class="services">SERVICES</li>
                <li class="why">WHY RESSWELL</li>
            </ul>
        </nav>
```

![image](https://user-images.githubusercontent.com/32041993/52764250-185f9400-2fd4-11e9-89d3-6a562bb4e720.png)
