### ISSUE TITLE
About Page - Aligning Section Text in Designated Text box 

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/Resswell#8]
Must figure out how to get this to go inside the box. 
Perhaps I can: 
1.  Just remove the following in CSS as it creates the background box
```css
.aboutnav {
    opacity: .6;
    width: 600px;
    background-color: white;
    height: 300px;
}
```

2. Then apply a background to each section instead?? Must try it tomorrow.. I'm sleepy now. 

```css

section {
    font-family: arial;
    font-weight: 50;
    font-size: 11pt;
    color: grey;
    width: 600px;
    height: 250px;
    margin-left: 45%;
    line-height: 1.6;
**background-color: white;** <- add this 
} 
```
![image](https://user-images.githubusercontent.com/32041993/52768903-a7c07380-2fe3-11e9-9e9f-f72c7af0e6cc.png)
